spring.application.name=spring-customer-management-restful
spring.datasource.url=jdbc:mysql://localhost:3306/customer_restful?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=codegym

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
