spring.application.name=customer-management-jpa
spring.datasource.url=jdbc:mysql://localhost:3306/product_jpa
spring.datasource.username=root
spring.datasource.password=codegym

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
